<a href="https://colab.research.google.com/github/Kvngdrvy/quick-tip/blob/main/Copy_of_QuickStart_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QuickStarter to the tournament

##Basic step and workflow:

0 - Using this notebook

1 - Download data

2 - Explore data

3 - Choose and train a model

4 - Scoring

5 - Make prediction

6 - Submit

---

# 0 - Using this notebook 

To execute the cell press `shift+enter`. 

Follow the steps and login with your Google account.

In [ ]:
# Lib & Dependencies
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import requests
from scipy import stats

# 1 - Download data

We will provide you with two dataset

- Training_data will be use to train your model.
- Hackathon_data will be use to make your prediciton.


There is three target you need to provide prediction on: target_r, target_g, target_b.

In [ ]:
# Data Download (may take a few minutes depending on your network)
train_datalink_X = 'https://tournament.crunchdao.com/data/X_train.csv'  
train_datalink_y = 'https://tournament.crunchdao.com/data/y_train.csv' 
hackathon_data_link = 'https://tournament.crunchdao.com/data/X_test.csv' 

# Data for training
train_data = pd.read_csv(train_datalink_X)
# Data for which you will submit your prediction
test_data = pd.read_csv(hackathon_data_link)
# Targets use for your supervised trainning
train_targets = pd.read_csv(train_datalink_y)

# If you don't want to work with time series
train_data = train_data.drop(columns=['Moons', 'id'])
test_data = test_data.drop(columns=['Moons', 'id'])

In [ ]:
display(train_data)
display(train_targets)
display(test_data)

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_104,Feature_105,Feature_106,Feature_107,Feature_108,Feature_109,Feature_110,Feature_111,Feature_112,Feature_113
0,0.75,0.50,0.75,0.25,0.50,0.50,0.50,0.00,0.00,0.00,...,0.50,1.00,0.75,1.00,1.00,0.50,0.75,0.50,0.75,0.00
1,0.00,0.75,0.00,0.00,0.00,0.25,0.25,0.25,0.25,0.25,...,0.50,0.50,0.25,1.00,0.75,0.75,0.75,0.50,1.00,0.50
2,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,0.00,1.00,0.00,1.00,0.00,1.00,0.50,0.75,0.75
3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.25,...,0.75,0.00,0.75,0.25,0.75,0.00,0.75,0.00,0.50,0.00
4,0.75,0.50,0.50,0.75,0.75,0.75,0.75,0.75,0.75,0.75,...,0.00,0.50,0.00,0.50,0.00,0.25,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567688,0.00,0.50,0.75,0.75,0.25,0.25,0.25,0.50,0.50,0.25,...,0.25,0.25,0.25,0.50,0.50,0.75,0.50,0.25,0.50,0.75
567689,0.75,0.50,0.25,0.50,0.25,0.25,0.50,0.50,0.50,0.75,...,0.25,0.25,0.25,0.75,0.25,0.50,0.25,0.25,0.25,0.25
567690,0.75,0.75,0.25,0.25,0.00,0.25,0.25,0.25,0.25,0.25,...,1.00,1.00,1.00,1.00,1.00,0.50,1.00,0.25,0.00,0.75
567691,0.50,0.75,0.75,0.75,0.25,0.25,0.25,0.75,0.75,0.75,...,0.50,0.25,0.50,0.75,0.75,0.00,0.75,0.75,0.75,0.25
567692,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.25,0.00,...,0.50,0.25,0.50,0.50,0.75,0.25,0.75,0.25,1.00,0.50

        target_r  target_g  target_b
0           0.25      0.25      0.25
1           0.25      0.25      0.25
2           0.75      0.00      0.00
3           0.75      0.00      0.00
4           0.50      0.50      0.25
...          ...       ...       ...
567688      1.00      0.25      0.00
567689      0.50      0.25      0.00
567690      0.00      0.00      0.00
567691      0.00      0.25      0.25
567692      0.75      0.75      0.00

[567693 rows x 3 columns]

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_104,Feature_105,Feature_106,Feature_107,Feature_108,Feature_109,Feature_110,Feature_111,Feature_112,Feature_113
0,0.25,0.25,0.00,0.25,0.25,0.25,0.25,0.25,0.25,0.25,...,0.00,1.00,0.50,1.00,0.25,0.75,0.25,0.75,0.00,0.00
1,0.00,0.00,0.00,0.00,0.25,0.00,0.25,0.00,0.00,0.00,...,0.75,0.75,0.75,0.00,0.75,0.50,0.50,0.50,0.50,0.25
2,0.00,0.25,0.25,0.25,0.25,0.00,0.00,0.00,0.25,0.00,...,0.25,0.00,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
3,0.25,0.50,0.25,0.25,0.25,0.50,0.50,0.50,0.50,0.75,...,0.25,0.75,0.00,0.50,0.00,0.25,0.00,0.00,0.00,0.00
4,0.75,0.75,0.75,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,0.50,1.00,0.75,1.00,0.75,1.00,0.75,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406687,0.25,0.50,0.25,0.25,0.25,0.25,0.50,1.00,1.00,1.00,...,1.00,0.00,1.00,0.00,1.00,0.00,1.00,0.75,0.25,0.00
406688,0.00,1.00,1.00,0.25,0.50,0.50,0.75,0.75,0.75,1.00,...,0.75,0.00,0.75,0.25,1.00,0.50,0.75,0.50,0.25,0.25
406689,0.75,0.75,0.50,0.75,0.75,0.50,0.50,0.50,0.50,0.50,...,0.75,0.00,0.75,0.00,0.75,0.25,0.75,0.50,0.25,0.00
406690,0.00,0.00,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.00,...,1.00,0.25,0.75,0.00,0.75,0.00,0.75,0.00,0.00,0.25
406691,0.75,0.75,0.75,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,0.00,0.75,0.00,0.50,0.00,0.75,0.25,0.75,0.25,0.50

# 2 - Explore Data

Observe your data and prepare carefully what you will give to your model for training.

In [ ]:
display(train_data.describe())
display(train_targets.describe())

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_104,Feature_105,Feature_106,Feature_107,Feature_108,Feature_109,Feature_110,Feature_111,Feature_112,Feature_113
count,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.00000,567693.000000,...,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000,567693.000000
mean,0.499679,0.499845,0.499852,0.499889,0.499902,0.499926,0.499916,0.499938,0.49993,0.499902,...,0.499954,0.499954,0.499954,0.499954,0.499954,0.499954,0.499954,0.298497,0.394858,0.437579
std,0.353703,0.353631,0.353612,0.353663,0.353620,0.353644,0.353635,0.353636,0.35364,0.353641,...,0.353633,0.353633,0.353633,0.353633,0.353633,0.353633,0.353633,0.253910,0.339992,0.350631
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.25000,0.250000,...,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.000000,0.000000,0.000000
50%,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.50000,0.500000,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.250000,0.250000,0.500000
75%,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.75000,0.750000,...,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.500000,0.750000,0.750000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

            target_r       target_g       target_b
count  567693.000000  567693.000000  567693.000000
mean        0.499954       0.499954       0.499954
std         0.353633       0.353633       0.353633
min         0.000000       0.000000       0.000000
25%         0.250000       0.250000       0.250000
50%         0.500000       0.500000       0.500000
75%         0.750000       0.750000       0.750000
max         1.000000       1.000000       1.000000

# 3 - Choose models

In [ ]:
def xg_boost_hackathon(data, target):
    X, y = data, target
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
    model = xgb.XGBRegressor(objective='reg:squarederror', max_depth=5, learning_rate=0.01, n_estimators=2000, n_jobs=-1, colsample_bytree=0.5)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    scorer(y_test, pred)

    return model

# 4 - Scoring: Spearman's rank correlation of your predictions vs the targets

In [ ]:
def scorer(y_test, y_pred):
    score = (stats.spearmanr(y_test, y_pred)*100)[0]
    print('Score as calculated for the leader board (っಠ‿ಠ)っ {}'.format(score))

# Supervised training of a simple XGBoost

In [ ]:
model_target_r = xg_boost_hackathon(train_data, train_targets.target_r)
model_target_g = xg_boost_hackathon(train_data, train_targets.target_g)
model_target_b = xg_boost_hackathon(train_data, train_targets.target_b)

Score as calculated for the leader board (っಠ‿ಠ)っ 0.141070359619914

# 5 - Make prediction on the 3 targets

When you feel like your model is accurate enough it's time to predict the target and submit your results.

Repeat the operation on the three targets, concatenate the answers and submit.

**WARNING** 1/ Keep the raw order identical.

**WARNING** 2/ Be sure that your columns are named target_r, target-g and
 target_b.

**WARNING** 3/ Your prediction need to be between 0 and 1.

**WARNING** 4/ Don't submit constant values.

In [ ]:
prediction = pd.DataFrame()
prediction['target_r'] = model_target_r.predict(test_data)
prediction['target_g'] = model_target_g.predict(test_data)
prediction['target_b'] = model_target_b.predict(test_data)

In [ ]:
prediction

# 6 - Submit predictions

Past <u>your</u> API key here. You received it by email upon registration and can retrieve it in your dashboard.

In [ ]:
API_KEY = "" # <- HERE

r = requests.post("https://tournament.crunchdao.com/api/v2/submissions",
    files = {
        "file": ("x", prediction.to_csv().encode('ascii'))
    },
    data = {
        "apiKey": API_KEY
    },
)

if r.status_code == 200:
    print("Submission submitted.")
elif r.status_code == 423:
    print("ERR: Submissions are close")
    print("You can only submit during rounds eg: Friday 7pm GMT+1 to Sunday midnight GMT+1.")
    print("Or the server is currently crunching the submitted files, please wait some time before retrying.")
elif r.status_code == 422:
    print("ERR: API Key is missing or empty")
    print("Did you forget to fill the API_KEY variable?")
elif r.status_code == 400:
    print("ERR: The file must not be empty")
    print("You have send a empty file.")
elif r.status_code == 401:
    print("ERR: Your email hasn't been verified")
    print("Please verify your email or contact a cruncher.")
elif r.status_code == 409:
    print("ERR: Duplicate submission")
    print("Your work has already been submitted with the same exact results, if you think that this a false positive, contact a cruncher.")
    print("MD5 collision probability: 1/2^128 (source: https://stackoverflow.com/a/288519/7292958)")
elif r.status_code == 429:
    print("ERR: Too many submissions")
else:
    print("ERR: Server returned: " + str(r.status_code))
    print("Ouch! It seems that we were not expecting this kind of result from the server, if the probleme persist, contact a cruncher.")

ERR: API Key is missing or empty
Did you forget to fill the API_KEY variable?

In [ ]:
# Downloads data
from google.colab import files
with open("prediciton.csv", "wb") as f:
    f.write(prediction.to_csv().encode('ascii'))
files.download('prediciton.csv')